Name:           ros-melodic-fetch-navigation
Version:        0.8.1
Release:        0%{?dist}
Summary:        ROS fetch_navigation package

Group:          Development/Libraries
License:        BSD
URL:            http://docs.fetchrobotics.com/navigation.html
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-amcl
Requires:       ros-melodic-base-local-planner
Requires:       ros-melodic-clear-costmap-recovery
Requires:       ros-melodic-costmap-2d
Requires:       ros-melodic-fetch-depth-layer
Requires:       ros-melodic-fetch-maps
Requires:       ros-melodic-map-server
Requires:       ros-melodic-move-base
Requires:       ros-melodic-move-base-msgs
Requires:       ros-melodic-navfn
Requires:       ros-melodic-rotate-recovery
Requires:       ros-melodic-slam-karto
Requires:       ros-melodic-voxel-grid
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-roslaunch

%description
Configuration and launch files for running ROS navigation on Fetch.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Apr 04 2019 Russell Toris <rtoris@fetchrobotics.com> - 0.8.1-0
- Autogenerated by Bloom

* Wed Feb 13 2019 Russell Toris <rtoris@fetchrobotics.com> - 0.8.0-0
- Autogenerated by Bloom

