Name:           ros-melodic-fetch-ikfast-plugin
Version:        0.8.1
Release:        0%{?dist}
Summary:        ROS fetch_ikfast_plugin package

Group:          Development/Libraries
License:        Apache2
URL:            http://docs.fetchrobotics.com/manipulation.html
Source0:        %{name}-%{version}.tar.gz

Requires:       lapack-devel
Requires:       ros-melodic-eigen-conversions
Requires:       ros-melodic-moveit-core
Requires:       ros-melodic-pluginlib
Requires:       ros-melodic-roscpp
BuildRequires:  lapack-devel
BuildRequires:  ros-melodic-catkin
BuildRequires:  ros-melodic-eigen-conversions
BuildRequires:  ros-melodic-moveit-core
BuildRequires:  ros-melodic-pluginlib
BuildRequires:  ros-melodic-roscpp
BuildRequires:  ros-melodic-tf2-eigen
BuildRequires:  ros-melodic-tf2-kdl

%description
Kinematics plugin for Fetch robot, generated through IKFast

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Apr 04 2019 Russell Toris <rtoris@fetchrobotics.com> - 0.8.1-0
- Autogenerated by Bloom

* Wed Feb 13 2019 Russell Toris <rtoris@fetchrobotics.com> - 0.8.0-0
- Autogenerated by Bloom

