Name:           ros-melodic-fetch-description
Version:        0.8.1
Release:        0%{?dist}
Summary:        ROS fetch_description package

Group:          Development/Libraries
License:        CreativeCommons-Attribution-NonCommercial-NoDerivatives-4.0
URL:            http://docs.fetchrobotics.com/robot_hardware.html
Source0:        %{name}-%{version}.tar.gz

Requires:       ros-melodic-urdf
Requires:       ros-melodic-xacro
BuildRequires:  ros-melodic-catkin

%description
URDF for Fetch Robot.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/melodic" \
        -DCMAKE_PREFIX_PATH="/opt/ros/melodic" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/melodic/setup.sh" ]; then . "/opt/ros/melodic/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/melodic

%changelog
* Thu Apr 04 2019 Russell Toris <rtoris@fetchrobotics.com> - 0.8.1-0
- Autogenerated by Bloom

* Wed Feb 13 2019 Russell Toris <rtoris@fetchrobotics.com> - 0.8.0-0
- Autogenerated by Bloom

